### ISSUE TITLE
Used deprecated method

### ISSUE THREAD

**Issue by mayaljh** [ealeksandrov/EAIntroView#112]
[EAIntroView.m]
titleHeight = [page.title sizeWithFont:page.titleFont constrainedToSize:CGSizeMake(self.scrollView.frame.size.width - 20, CGFLOAT_MAX) lineBreakMode:NSLineBreakByWordWrapping].height;

![2015-05-24 3 26 42](https://cloud.githubusercontent.com/assets/6308111/7786948/4dbd969c-0229-11e5-95b4-f7443b72ab0e.png)

[sizeWithFont:constrainedToSize:lineBreakMode:] Method is deprecated in iOS7.
So Apple recommend to use [Use boundingRectWithSize:options:attributes:context:] instead.
How can I change to new method?

**Comment by ealeksandrov** [comment]
Please update to latest version. This issue was originally reported in #6, conditionally fixed in 3e850a03f3aa2414c6b69b0b61407b45c3149c21 and even dropped at all in current version: [EAIntroView.m#L356](https://github.com/ealeksandrov/EAIntroView/blob/eafe7e412eb1c1b8bb80338c34fa2b0def811b06/EAIntroView/EAIntroView.m#L356)
