### ISSUE TITLE
In modem or in-call mode the interface moves upward.

### ISSUE THREAD

**Issue by temasnow** [ealeksandrov/EAIntroView#113]
Constraints some reason do not work and some part of TabBar becomes visible.. 
![ios simulator screen shot 01 jun 2015 15 30 07](https://cloud.githubusercontent.com/assets/3713547/7912809/334b3a30-0873-11e5-9ad9-7ee90d1eda55.png)

**Comment by ealeksandrov** [comment]
Hey,

How are you handling presentation of introView? `showInView` or `showFullscreen`?

**Comment by temasnow** [comment]
Hey, 
```
[intro showFullscreenWithAnimateDuration:0.3];
```

**Comment by ealeksandrov** [comment]
I cannot reproduce this issue wit current version of EAIntroView - for `showInView:animateDuration:` it collapses vertically, for `showFullscreen` - just stays underneath (because it uses different UIWindow). None of tests shows bottom bar.

![screenshot 2015-07-09 22 53 38](https://cloud.githubusercontent.com/assets/3132438/8605372/82d9ef0a-268d-11e5-9d5e-a157e9654a4e.png) 
![screenshot 2015-07-09 22 53 51](https://cloud.githubusercontent.com/assets/3132438/8605374/86f69dea-268d-11e5-9b56-9dcb71adbf21.png)

**Comment by marinotws** [comment]
idem ... 
![schermata 2015-07-15 alle 15 23 48](https://cloud.githubusercontent.com/assets/8616947/8699411/9571b3ce-2b05-11e5-8db2-2fd9ab63a040.png)

**Comment by ealeksandrov** [comment]
@marinotws looks like you are presenting IntroView on inner view of TabBarController. You should use `showFullscreen` or `showInView:tabBarController.view`. I can't say much without demo code. Feel free to send it by email.

**Comment by marinotws** [comment]
@ealeksandrov  hello, I used showFullscreen and/or showInView:tabBarController.view ... the problem is always the same

**Comment by ealeksandrov** [comment]
Can't help since my simple implementation is working well. If you can recreate wrong behaviour in small demo project - please share it here or by email.

**Comment by ealeksandrov** [comment]
Feel free to reopen with some sample code related to this issue.
