### ISSUE TITLE
Swipe gesture not always responsive

### ISSUE THREAD

**Issue by jegumi** [ealeksandrov/EAIntroView#77]
The behaviour of the swipe gesture is quite erratic. Sometimes I swipe a couple of views and stop to response in one direction, of during some seconds. Perhaps it's due to a wrong config from my side. Anybody with this issue?. By the way I'm using the storyboard integrated view

**Comment by ealeksandrov** [comment]
Closed until further details or reproduced demo.

**Comment by wdcurry** [comment]
I can reproduce this 100% of the time in my app, but cannot bring that to here as the app is complex in design and implementation. It ONLY happens when i log out of my app and return to a "Guest Menu". When i fire up the intro view from after logout, it freezes (but runs without error). If i then fire the app up directly into the guest menu there are no issues with swiping.
