### ISSUE TITLE
Rotation support

### ISSUE THREAD

**Issue by fulldecent** [ealeksandrov/EAIntroView#79]
Issue #19 is a closed issue that discusses orientation.

The demo app does not implement the orientation fixes.

![screen shot 2014-10-05 at 12 48 16 pm](https://cloud.githubusercontent.com/assets/382183/4519121/6b6ce51a-4caf-11e4-9e23-f7f326d5385a.png)

**Comment by ealeksandrov** [comment]
Blocked by #100

**Comment by funnel20** [comment]
I did manage to adjust EAIntroView.m with a few changes to have rotation support.
The bottom line that should happen is:
1. Adjust scrollview
2. Adjust contentSize of ScrollView
3. Adjust frame of each page
4. Adjust scrolling to fit resized page
5. Adjust restricted scroll area
6. Correctly reposition the page objects: titleIconView, title and desc.

I have done point 1 in `- (EARestrictedScrollView *)scrollView {` by correcting autoresizingMask:
```
_scrollView.autoresizingMask = UIViewAutoresizingFlexibleHeight | UIViewAutoresizingFlexibleWidth;
```
Points 2 till 5 are covered in a new method that is the resulted of a device rotation notification:
```
#pragma mark - Notifications

- (void)deviceOrientationDidChange:(NSNotification *)notification {    
    // Get amount of pages:
    NSInteger numberOfPages = _pages.count;
    
    // Increase with 1 page when feature enabled:
    if (self.swipeToExit) {
        numberOfPages = numberOfPages + 1;
    }
    
    // Adjust contentSize of ScrollView:
    self.scrollView.contentSize = CGSizeMake(numberOfPages * self.scrollView.frame.size.width, self.scrollView.frame.size.height);
    
    // Adjust frame of each page:
    NSUInteger i = 0;
    for (EAIntroPage *page in _pages) {
        page.pageView.frame = CGRectMake(i * self.scrollView.bounds.size.width,
                                         0,
                                         self.scrollView.bounds.size.width,
                                         self.scrollView.bounds.size.height);
        i++;
    }
    
    // Adjust scrolling to fit resized page:
    CGFloat offset = self.currentPageIndex * self.scrollView.frame.size.width;
    CGRect pageRect = { .origin.x = offset, .origin.y = 0.0, .size.width = self.scrollView.frame.size.width, .size.height = self.scrollView.frame.size.height };
    [self.scrollView scrollRectToVisible:pageRect animated:NO];
    
    // Adjust restricted scroll area:
    if(!self.scrollingEnabled) {
        self.scrollView.restrictionArea = CGRectMake(self.visiblePageIndex * self.bounds.size.width, 0, self.scrollView.bounds.size.width, self.scrollView.bounds.size.height);
    }
    else {
        self.scrollView.restrictionArea = CGRectZero;
    }
}
```
To receive this notification, I added an observer to `- (void)applyDefaultsToSelfDuringInitializationWithFrame:(CGRect)frame pages:(NSArray *)pagesArray {`:
```
// Add observer for device orientation:
    [[UIDevice currentDevice] beginGeneratingDeviceOrientationNotifications];
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(deviceOrientationDidChange:)
                                                 name:UIDeviceOrientationDidChangeNotification
                                               object:nil];
```
The observer is removed in `- (void)finishIntroductionAndRemoveSelf {`:
```
// Remove observer for rotation:
    [[NSNotificationCenter defaultCenter] removeObserver:self];
    [[UIDevice currentDevice] endGeneratingDeviceOrientationNotifications];
```
Now point 6 remains. I have a difficulty with this, because the decision that titlePositionY and descPositionY are from the bottom of the screen. To solve it, I added the following autoresizingMask to all 3 objects in `- (UIView *)viewForPage:(EAIntroPage *)page atXIndex:(CGFloat)xIndex {`:
```
titleImageView.autoresizingMask = UIViewAutoresizingFlexibleLeftMargin | UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;

titleLabel.autoresizingMask = UIViewAutoresizingFlexibleLeftMargin | UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleTopMargin;

descLabel.autoresizingMask = UIViewAutoresizingFlexibleLeftMargin | UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleTopMargin;
```
However, the problem with the title and the description is that in my app (see #99 ) I have positioned these to the top of the screen, by using a large titlePositionY (`[UIScreen mainScreen].bounds.size.height - 50.0;`). So when using UIViewAutoresizingFlexibleTopMargin, these objects are being pushed above the visible screen when rotating from Portrait to Landscape. In my case I used UIViewAutoresizingFlexibleBottomMargin.
So for point 6 I have no generic solution. I hope you can find one, based on the information that I provided.

**Comment by funnel20** [comment]
Rotating from Portrait to Landscape will now properly reposition the items, especially my custom button "Begin". This was impossible before, since the page's frame was not resized, so the button always stayed at the wrong place, no matter with autoresizingMask or constraint settings I used.
![screen shot 2015-03-29 at 19 02 12](https://cloud.githubusercontent.com/assets/2139844/6886686/7528b78e-d646-11e4-9997-411f563fe0f5.png)

Rotation to landscape is now perfect:
![screen shot 2015-03-29 at 19 02 18](https://cloud.githubusercontent.com/assets/2139844/6886687/83b68312-d646-11e4-9c3f-e20495fc9845.png)

**Comment by funnel20** [comment]
I hope all of these helps you to implement this feature request.

**Comment by ealeksandrov** [comment]
Thanks a lot for details on your implementation! Looks interesting. I already fixed blocking bug, will do some refactor and move to this issue soon.

**Comment by judepereira** [comment]
@funnel20: Brilliant work there! Got it working :)

**Comment by georgbachmann** [comment]
@funnel20 thanks... solved my issue!

**Comment by funnel20** [comment]
You're welcome. I hoped it would have been merged already in the main branch.

**Comment by ealeksandrov** [comment]
@funnel20 thanks a lot, that's a great solution. I pushed this to master branch.

Now I will think more about adding constraints between page items (title, desc, etc), not just offset from top/bottom. Or maybe choice between constraints or coordinate offsets.

**Comment by ealeksandrov** [comment]
![screenshot 2015-07-21 17 47 13](https://cloud.githubusercontent.com/assets/3132438/8803634/8f78ccee-2fd0-11e5-8ac8-205992c25cf8.png)
![screenshot 2015-07-21 17 47 16](https://cloud.githubusercontent.com/assets/3132438/8803635/903c3332-2fd0-11e5-9315-60a8b9bf49d4.png)

**Comment by funnel20** [comment]
Great!
