### ISSUE TITLE
Not working without autoresizing masks

### ISSUE THREAD

**Issue by caramdache** [ealeksandrov/EAIntroView#87]
One of the very recent release broke one my apps which uses a UISplitViewController:

* the screen is black
* the title and desc texts sit in the lower right corner.

Not sure what changes broke it in EAIntroView, but last pull was from a few weeks ago and there was no issue then (and my app code has not changed in that area).

I'll send a sample project by email.

**Comment by ealeksandrov** [comment]
Sorry, I can't access it. Please sent it directly to evgeny@aleksandrov.ws or upload to Mega/Sendspace/etc.
I am working on 3.0 release now, so I will get to this bug immediately on receiving from you.

**Comment by ealeksandrov** [comment]
Thanks for sending this to me.
```
splitViewController.view.translatesAutoresizingMaskIntoConstraints = NO;
```
this line conflicts with current implementation, because we are using `autoresizingMask` inside `EAIntroView` - this is due to autolayout inconsistency in iOS 6 & 7. In v3.0 I will transition everything to constraints, so this issue should disappear. But lets keep it until then and recheck before 3.0 release.

**Comment by ealeksandrov** [comment]
In 81c1f612f3c8c8dbbc434e55b1436d68de60b54b I added [`showFullscreen`](https://github.com/ealeksandrov/EAIntroView/blob/81c1f612f3c8c8dbbc434e55b1436d68de60b54b/EAIntroView/EAIntroView.h#L72-74) set of actions. It will find topmost window and show intro there. Since it is not linked to your customized view - intro will work and resize fine.
Tested in your example project - working ok.
